config/routes.rb
Rails.application.routes.draw do
  get 'inventory/index'

  resources :line_items

  resources :issuances

  resources :tools

  root 'inventory#index', as: 'inventory'

end

app/models/issuance.rb
class Issuance < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_tool(tool_id)
    current_item = line_items.find_by(tool_id: tool_id)
    if current_item
      errors.add(:tool_id, "has already been added")
    else
      current_item = line_items.build(tool_id: tool_id)
    end
    current_item
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :tool
  belongs_to :issuance
end

app/models/tool.rb
class Tool < ActiveRecord::Base
  has_many :line_items

  before_destroy :ensure_not_referenced_by_any_line_item

  private

    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, "Line Items present")
        return false
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/current_issuance.rb
module CurrentIssuance
  extend ActiveSupport::Concern

  private

    def set_issuance
      @issuance = Issuance.find(session[:issuance_id])
    rescue ActiveRecord::RecordNotFound
      @issuance = Issuance.create
      session[:issuance_id] = @issuance.id
    end
end

app/controllers/inventory_controller.rb
class InventoryController < ApplicationController
  include CurrentIssuance
  before_action :set_issuance
  def index
    @tools = Tool.order(:description)
  end
end

app/controllers/issuances_controller.rb
class IssuancesController < ApplicationController
  before_action :set_issuance, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_issuance

  # GET /issuances
  # GET /issuances.json
  def index
    @issuances = Issuance.all
  end

  # GET /issuances/1
  # GET /issuances/1.json
  def show
  end

  # GET /issuances/new
  def new
    @issuance = Issuance.new
  end

  # GET /issuances/1/edit
  def edit
  end

  # POST /issuances
  # POST /issuances.json
  def create
    @issuance = Issuance.new(issuance_params)

    respond_to do |format|
      if @issuance.save
        format.html { redirect_to @issuance, notice: 'Issuance was successfully created.' }
        format.json { render :show, status: :created, location: @issuance }
      else
        format.html { render :new }
        format.json { render json: @issuance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issuances/1
  # PATCH/PUT /issuances/1.json
  def update
    respond_to do |format|
      if @issuance.update(issuance_params)
        format.html { redirect_to @issuance, notice: 'Issuance was successfully updated.' }
        format.json { render :show, status: :ok, location: @issuance }
      else
        format.html { render :edit }
        format.json { render json: @issuance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issuances/1
  # DELETE /issuances/1.json
  def destroy
    @issuance.destroy if @issuance.id == session[:issuance_id]
    session[:issuance_id] = nil
    respond_to do |format|
      format.html { redirect_to issuances_url, notice: 'Issuance was successfully descarded.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issuance
      @issuance = Issuance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issuance_params
      params[:issuance]
    end

    def invalid_issuance
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, notice: 'Invalid cart'
    end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentIssuance
  before_action :set_issuance, only: [:create]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    tool = Tool.find(params[:tool_id])
    @line_item = @issuance.add_tool(tool.id)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to inventory_url }
        format.js
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:tool_id)
    end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_action :set_tool, only: [:show, :edit, :update, :destroy]

  # GET /tools
  # GET /tools.json
  def index
    @tools = Tool.all
  end

  # GET /tools/1
  # GET /tools/1.json
  def show
  end

  # GET /tools/new
  def new
    @tool = Tool.new
  end

  # GET /tools/1/edit
  def edit
  end

  # POST /tools
  # POST /tools.json
  def create
    @tool = Tool.new(tool_params)

    respond_to do |format|
      if @tool.save
        format.html { redirect_to @tool, notice: 'Tool was successfully created.' }
        format.json { render :show, status: :created, location: @tool }
      else
        format.html { render :new }
        format.json { render json: @tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tools/1
  # PATCH/PUT /tools/1.json
  def update
    respond_to do |format|
      if @tool.update(tool_params)
        format.html { redirect_to @tool, notice: 'Tool was successfully updated.' }
        format.json { render :show, status: :ok, location: @tool }
      else
        format.html { render :edit }
        format.json { render json: @tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tools/1
  # DELETE /tools/1.json
  def destroy
    @tool.destroy
    respond_to do |format|
      format.html { redirect_to tools_url, notice: 'Tool was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tool
      @tool = Tool.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tool_params
      params.require(:tool).permit(:tool_barcode, :description, :quantity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/helpers/issuances_helper.rb
module IssuancesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/inventory/index.html.erb
<div class="page-header">
  <h1>Issue Tool</h1>
</div>

<% if notice %>
  <p><%= notice %></p>
<% end %>


<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <th>Tool Barcode</th>
      <th>Description</th>
      <th></th>
    </thead>

    <tbody>
      <% @tools.each do |tool| %>
        <tr>
          <td><%= tool.tool_barcode %></td>
          <td><%= sanitize(tool.description) %></td>
          <td><%= button_to 'Add to issuance', line_items_path(tool_id: tool), remote: true %></td>
        </tr>
        <div>
          <%#= button_to 'Add Tool', line_items_path(tool_id: tool), remote: true %>
        </div>
      <% end %>
    </tbody>
  </table>
</div><br><br>

<div id="issuance">
  <%= render @issuance %>
</div>

app/views/issuances/_form.html.erb
<%= form_for(@issuance) do |f| %>
  <% if @issuance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issuance.errors.count, "error") %> prohibited this issuance from being saved:</h2>

      <ul>
      <% @issuance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issuances/_issuance.html.erb
<div class="page-header">
  <h1>Cart No. <%= issuance.id %></h1>
</div>

<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Tool Barcode</th>
        <th>Description</th>
      </tr>
    </thead>

    <tbody>
      <%= render(issuance.line_items) %>
    </tbody>
  
  </table>
</div>
<%= button_to 'Discard Issuance', @issuance, method: :delete, data: {confirm: 'Are you sure?'} %>
<%#= link_to 'Edit', edit_issuance_path(@issuance) %> |
<%#= link_to 'Back', issuances_path %>

app/views/issuances/edit.html.erb
<h1>Editing issuance</h1>

<%= render 'form' %>

<%= link_to 'Show', @issuance %> |
<%= link_to 'Back', issuances_path %>

app/views/issuances/index.html.erb
<h1>Listing issuances</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issuances.each do |issuance| %>
      <tr>
        <td><%= link_to 'Show', issuance %></td>
        <td><%= link_to 'Edit', edit_issuance_path(issuance) %></td>
        <td><%= link_to 'Destroy', issuance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issuance', new_issuance_path %>

app/views/issuances/new.html.erb
<h1>New issuance</h1>

<%= render 'form' %>

<%= link_to 'Back', issuances_path %>

app/views/issuances/show.html.erb
<% if notice %>
  <p><%= notice %></p>
<% end %>

<div class="table-responsive">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Tool Barcode</th>
				<th>Description</th>
			</tr>
		</thead>

		<tbody>
			<%= render @issuance %>
		</tbody>
	</table>
</div>

<%= button_to 'Discard Issuance', @issuance, method: :delete, data: {confirm: 'Are you sure?'} %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Inventory', inventory_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Tools', tools_path %></li>
        <li><%= link_to 'New Issuance', new_issuance_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tooltest</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    
    <%= render 'layouts/nav' %>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tool_id %><br>
    <%= f.text_field :tool_id %>
  </div>
  <div class="field">
    <%= f.label :issuance_id %><br>
    <%= f.text_field :issuance_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<tr>
  <td><%= line_item.tool.tool_barcode %></td>
  <td><%= line_item.tool.description %></td>
</tr>

app/views/line_items/create.js.erb
$('#issuance').html("<%= escape_javascript render(@issuance) %>");

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <thead>
    <tr>
      <th>Tool</th>
      <th>Issuance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.tool %></td>
        <td><%= line_item.issuance %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tool:</strong>
  <%= @line_item.tool %>
</p>

<p>
  <strong>Issuance:</strong>
  <%= @line_item.issuance %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

app/views/tools/_form.html.erb
<%= form_for(@tool) do |f| %>
  <% if @tool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tool.errors.count, "error") %> prohibited this tool from being saved:</h2>

      <ul>
      <% @tool.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tool_barcode %><br>
    <%= f.text_field :tool_barcode %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tools/edit.html.erb
<h1>Editing tool</h1>

<%= render 'form' %>

<%= link_to 'Show', @tool %> |
<%= link_to 'Back', tools_path %>

app/views/tools/index.html.erb
<h1>Listing tools</h1>

<div class="table-responsive">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Tool barcode</th>
      <th>Description</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tools.each do |tool| %>
      <tr>
        <td><%= tool.tool_barcode %></td>
        <td><%= tool.description %></td>
        <td><%= tool.quantity %></td>
        <td><%= link_to 'Show', tool %></td>
        <td><%= link_to 'Edit', edit_tool_path(tool) %></td>
        <td><%= link_to 'Destroy', tool, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Tool', new_tool_path %>

app/views/tools/new.html.erb
<h1>New tool</h1>

<%= render 'form' %>

<%= link_to 'Back', tools_path %>

app/views/tools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tool barcode:</strong>
  <%= @tool.tool_barcode %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tool.description %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @tool.quantity %>
</p>

<%= link_to 'Edit', edit_tool_path(@tool) %> |
<%= link_to 'Back', tools_path %>